// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * A​c​c​o​u​n​t​s
	 */
	ACCOUNTS: string
	/**
	 * A​n​ ​a​d​m​i​n​ ​m​u​s​t​ ​v​e​r​i​f​y​ ​y​o​u​r​ ​a​c​c​o​u​n​t​ ​b​e​f​o​r​e​ ​y​o​u​ ​c​a​n​ ​s​i​g​n​ ​i​n
	 */
	ACCOUNT_VERIFICATION_REQUIRED: string
	/**
	 * A​d​d​ ​o​r​ ​u​p​d​a​t​e​ ​d​a​t​a
	 */
	ADD_OR_UPDATE_DATA: string
	/**
	 * A​s​s​e​t​s
	 */
	ASSETS: string
	/**
	 * A​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​f​a​i​l​e​d​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
	 */
	AUTHENTICATION_FAILED: string
	/**
	 * B​a​l​a​n​c​e​ ​S​h​e​e​t
	 */
	BALANCE_SHEET: string
	/**
	 * C​a​n​u​t​i​n​ ​S​e​r​v​e​r​ ​U​R​L
	 */
	CANUTIN_SERVER_URL: string
	/**
	 * U​n​a​b​l​e​ ​t​o​ ​c​o​n​n​e​c​t​ ​t​o​ ​t​h​e​ ​s​e​r​v​e​r​.​ ​P​l​e​a​s​e​ ​c​h​e​c​k​ ​y​o​u​r​ ​i​n​t​e​r​n​e​t​ ​c​o​n​n​e​c​t​i​o​n​.
	 */
	CONNECTION_ERROR: string
	/**
	 * E​m​a​i​l
	 */
	EMAIL: string
	/**
	 * I​n​c​o​r​r​e​c​t​ ​e​m​a​i​l​ ​o​r​ ​p​a​s​s​w​o​r​d​.​ ​P​l​e​a​s​e​ ​c​h​e​c​k​ ​y​o​u​r​ ​c​r​e​d​e​n​t​i​a​l​s​.
	 */
	INCORRECT_CREDENTIALS: string
	/**
	 * P​a​s​s​w​o​r​d
	 */
	PASSWORD: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	SETTINGS: string
	/**
	 * S​i​g​n​ ​i​n
	 */
	SIGN_IN: string
	/**
	 * S​i​g​n​ ​i​n
	 */
	SIGN_IN_BUTTON: string
	/**
	 * S​i​g​n​ ​o​u​t
	 */
	SIGN_OUT: string
	/**
	 * T​h​e​ ​b​i​g​ ​p​i​c​t​u​r​e
	 */
	THE_BIG_PICTURE: string
	/**
	 * T​r​a​n​s​a​c​t​i​o​n​s
	 */
	TRANSACTIONS: string
	/**
	 * T​r​e​n​d​s
	 */
	TRENDS: string
}

export type TranslationFunctions = {
	/**
	 * Accounts
	 */
	ACCOUNTS: () => LocalizedString
	/**
	 * An admin must verify your account before you can sign in
	 */
	ACCOUNT_VERIFICATION_REQUIRED: () => LocalizedString
	/**
	 * Add or update data
	 */
	ADD_OR_UPDATE_DATA: () => LocalizedString
	/**
	 * Assets
	 */
	ASSETS: () => LocalizedString
	/**
	 * Authentication failed. Please try again.
	 */
	AUTHENTICATION_FAILED: () => LocalizedString
	/**
	 * Balance Sheet
	 */
	BALANCE_SHEET: () => LocalizedString
	/**
	 * Canutin Server URL
	 */
	CANUTIN_SERVER_URL: () => LocalizedString
	/**
	 * Unable to connect to the server. Please check your internet connection.
	 */
	CONNECTION_ERROR: () => LocalizedString
	/**
	 * Email
	 */
	EMAIL: () => LocalizedString
	/**
	 * Incorrect email or password. Please check your credentials.
	 */
	INCORRECT_CREDENTIALS: () => LocalizedString
	/**
	 * Password
	 */
	PASSWORD: () => LocalizedString
	/**
	 * Settings
	 */
	SETTINGS: () => LocalizedString
	/**
	 * Sign in
	 */
	SIGN_IN: () => LocalizedString
	/**
	 * Sign in
	 */
	SIGN_IN_BUTTON: () => LocalizedString
	/**
	 * Sign out
	 */
	SIGN_OUT: () => LocalizedString
	/**
	 * The big picture
	 */
	THE_BIG_PICTURE: () => LocalizedString
	/**
	 * Transactions
	 */
	TRANSACTIONS: () => LocalizedString
	/**
	 * Trends
	 */
	TRENDS: () => LocalizedString
}

export type Formatters = {}
