// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * A​c​c​o​u​n​t​s
	 */
	ACCOUNTS: string
	/**
	 * A​c​c​o​u​n​t​ ​t​y​p​e
	 */
	ACCOUNT_TYPE: string
	/**
	 * A​n​ ​a​d​m​i​n​ ​m​u​s​t​ ​v​e​r​i​f​y​ ​y​o​u​r​ ​a​c​c​o​u​n​t​ ​b​e​f​o​r​e​ ​y​o​u​ ​c​a​n​ ​s​i​g​n​ ​i​n
	 */
	ACCOUNT_VERIFICATION_REQUIRED: string
	/**
	 * A​d​d​ ​o​r​ ​u​p​d​a​t​e​ ​d​a​t​a
	 */
	ADD_OR_UPDATE_DATA: string
	/**
	 * A​s​s​e​t​ ​t​y​p​e
	 */
	ASSET_TYPE: string
	/**
	 * A​s​s​e​t​s
	 */
	ASSETS: string
	/**
	 * A​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​f​a​i​l​e​d​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
	 */
	AUTHENTICATION_FAILED: string
	/**
	 * A​u​t​o​-​c​a​l​c​u​l​a​t​e​d
	 */
	AUTO_CALCULATED: string
	/**
	 * B​a​l​a​n​c​e
	 */
	BALANCE: string
	/**
	 * B​a​l​a​n​c​e​ ​p​e​r​ ​m​o​n​t​h
	 */
	BALANCE_PER_MONTH: string
	/**
	 * B​a​l​a​n​c​e​ ​s​h​e​e​t
	 */
	BALANCE_SHEET: string
	/**
	 * B​a​l​a​n​c​e​ ​t​y​p​e
	 */
	BALANCE_TYPE: string
	/**
	 * C​a​n​u​t​i​n​ ​s​e​r​v​e​r​ ​U​R​L
	 */
	CANUTIN_SERVER_URL: string
	/**
	 * C​a​s​h
	 */
	CASH: string
	/**
	 * C​a​s​h​f​l​o​w
	 */
	CASHFLOW: string
	/**
	 * U​n​a​b​l​e​ ​t​o​ ​c​o​n​n​e​c​t​ ​t​o​ ​t​h​e​ ​s​e​r​v​e​r​.​ ​P​l​e​a​s​e​ ​c​h​e​c​k​ ​y​o​u​r​ ​i​n​t​e​r​n​e​t​ ​c​o​n​n​e​c​t​i​o​n​.
	 */
	CONNECTION_ERROR: string
	/**
	 * C​o​s​t
	 */
	COST: string
	/**
	 * D​e​b​t
	 */
	DEBT: string
	/**
	 * E​m​a​i​l
	 */
	EMAIL: string
	/**
	 * E​r​r​o​r
	 */
	ERROR: string
	/**
	 * E​x​p​e​n​s​e​s​ ​p​e​r​ ​m​o​n​t​h
	 */
	EXPENSES_PER_MONTH: string
	/**
	 * I​n​c​o​m​e​ ​p​e​r​ ​m​o​n​t​h
	 */
	INCOME_PER_MONTH: string
	/**
	 * I​n​c​o​r​r​e​c​t​ ​e​m​a​i​l​ ​o​r​ ​p​a​s​s​w​o​r​d​.​ ​P​l​e​a​s​e​ ​c​h​e​c​k​ ​y​o​u​r​ ​c​r​e​d​e​n​t​i​a​l​s​.
	 */
	INCORRECT_CREDENTIALS: string
	/**
	 * I​n​s​t​i​t​u​t​i​o​n
	 */
	INSTITUTION: string
	/**
	 * I​n​t​e​r​n​a​l​ ​s​e​r​v​e​r​ ​e​r​r​o​r
	 */
	INTERNAL_SERVER_ERROR: string
	/**
	 * I​n​v​e​s​t​m​e​n​t​s
	 */
	INVESTMENTS: string
	/**
	 * L​a​s​t​ ​u​p​d​a​t​e​d
	 */
	LAST_UPDATED: string
	/**
	 * N​a​m​e
	 */
	NAME: string
	/**
	 * N​e​t​ ​w​o​r​t​h
	 */
	NET_WORTH: string
	/**
	 * N​o​ ​a​c​c​o​u​n​t​s​ ​f​o​u​n​d
	 */
	NO_ACCOUNTS_FOUND: string
	/**
	 * N​o​ ​a​s​s​e​t​s​ ​f​o​u​n​d
	 */
	NO_ASSETS_FOUND: string
	/**
	 * N​o​t​ ​f​o​u​n​d
	 */
	NOT_FOUND: string
	/**
	 * O​t​h​e​r​ ​a​s​s​e​t​s
	 */
	OTHER_ASSETS: string
	/**
	 * P​a​s​s​w​o​r​d
	 */
	PASSWORD: string
	/**
	 * P​r​e​v​i​o​u​s​ ​1​2​ ​m​o​n​t​h​s
	 */
	PREVIOUS_12_MONTHS: string
	/**
	 * P​r​e​v​i​o​u​s​ ​6​ ​m​o​n​t​h​s
	 */
	PREVIOUS_6_MONTHS: string
	/**
	 * Q​u​a​n​t​i​t​y
	 */
	QUANTITY: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	SETTINGS: string
	/**
	 * S​i​g​n​ ​i​n
	 */
	SIGN_IN: string
	/**
	 * S​i​g​n​ ​i​n
	 */
	SIGN_IN_BUTTON: string
	/**
	 * S​i​g​n​ ​o​u​t
	 */
	SIGN_OUT: string
	/**
	 * S​u​m​m​a​r​y
	 */
	SUMMARY: string
	/**
	 * S​y​m​b​o​l
	 */
	SYMBOL: string
	/**
	 * T​h​e​ ​b​i​g​ ​p​i​c​t​u​r​e
	 */
	THE_BIG_PICTURE: string
	/**
	 * T​r​a​i​l​i​n​g​ ​c​a​s​h​f​l​o​w
	 */
	TRAILING_CASHFLOW: string
	/**
	 * T​r​a​n​s​a​c​t​i​o​n​s
	 */
	TRANSACTIONS: string
	/**
	 * T​r​e​n​d​s
	 */
	TRENDS: string
	/**
	 * V​a​l​u​e
	 */
	VALUE: string
}

export type TranslationFunctions = {
	/**
	 * Accounts
	 */
	ACCOUNTS: () => LocalizedString
	/**
	 * Account type
	 */
	ACCOUNT_TYPE: () => LocalizedString
	/**
	 * An admin must verify your account before you can sign in
	 */
	ACCOUNT_VERIFICATION_REQUIRED: () => LocalizedString
	/**
	 * Add or update data
	 */
	ADD_OR_UPDATE_DATA: () => LocalizedString
	/**
	 * Asset type
	 */
	ASSET_TYPE: () => LocalizedString
	/**
	 * Assets
	 */
	ASSETS: () => LocalizedString
	/**
	 * Authentication failed. Please try again.
	 */
	AUTHENTICATION_FAILED: () => LocalizedString
	/**
	 * Auto-calculated
	 */
	AUTO_CALCULATED: () => LocalizedString
	/**
	 * Balance
	 */
	BALANCE: () => LocalizedString
	/**
	 * Balance per month
	 */
	BALANCE_PER_MONTH: () => LocalizedString
	/**
	 * Balance sheet
	 */
	BALANCE_SHEET: () => LocalizedString
	/**
	 * Balance type
	 */
	BALANCE_TYPE: () => LocalizedString
	/**
	 * Canutin server URL
	 */
	CANUTIN_SERVER_URL: () => LocalizedString
	/**
	 * Cash
	 */
	CASH: () => LocalizedString
	/**
	 * Cashflow
	 */
	CASHFLOW: () => LocalizedString
	/**
	 * Unable to connect to the server. Please check your internet connection.
	 */
	CONNECTION_ERROR: () => LocalizedString
	/**
	 * Cost
	 */
	COST: () => LocalizedString
	/**
	 * Debt
	 */
	DEBT: () => LocalizedString
	/**
	 * Email
	 */
	EMAIL: () => LocalizedString
	/**
	 * Error
	 */
	ERROR: () => LocalizedString
	/**
	 * Expenses per month
	 */
	EXPENSES_PER_MONTH: () => LocalizedString
	/**
	 * Income per month
	 */
	INCOME_PER_MONTH: () => LocalizedString
	/**
	 * Incorrect email or password. Please check your credentials.
	 */
	INCORRECT_CREDENTIALS: () => LocalizedString
	/**
	 * Institution
	 */
	INSTITUTION: () => LocalizedString
	/**
	 * Internal server error
	 */
	INTERNAL_SERVER_ERROR: () => LocalizedString
	/**
	 * Investments
	 */
	INVESTMENTS: () => LocalizedString
	/**
	 * Last updated
	 */
	LAST_UPDATED: () => LocalizedString
	/**
	 * Name
	 */
	NAME: () => LocalizedString
	/**
	 * Net worth
	 */
	NET_WORTH: () => LocalizedString
	/**
	 * No accounts found
	 */
	NO_ACCOUNTS_FOUND: () => LocalizedString
	/**
	 * No assets found
	 */
	NO_ASSETS_FOUND: () => LocalizedString
	/**
	 * Not found
	 */
	NOT_FOUND: () => LocalizedString
	/**
	 * Other assets
	 */
	OTHER_ASSETS: () => LocalizedString
	/**
	 * Password
	 */
	PASSWORD: () => LocalizedString
	/**
	 * Previous 12 months
	 */
	PREVIOUS_12_MONTHS: () => LocalizedString
	/**
	 * Previous 6 months
	 */
	PREVIOUS_6_MONTHS: () => LocalizedString
	/**
	 * Quantity
	 */
	QUANTITY: () => LocalizedString
	/**
	 * Settings
	 */
	SETTINGS: () => LocalizedString
	/**
	 * Sign in
	 */
	SIGN_IN: () => LocalizedString
	/**
	 * Sign in
	 */
	SIGN_IN_BUTTON: () => LocalizedString
	/**
	 * Sign out
	 */
	SIGN_OUT: () => LocalizedString
	/**
	 * Summary
	 */
	SUMMARY: () => LocalizedString
	/**
	 * Symbol
	 */
	SYMBOL: () => LocalizedString
	/**
	 * The big picture
	 */
	THE_BIG_PICTURE: () => LocalizedString
	/**
	 * Trailing cashflow
	 */
	TRAILING_CASHFLOW: () => LocalizedString
	/**
	 * Transactions
	 */
	TRANSACTIONS: () => LocalizedString
	/**
	 * Trends
	 */
	TRENDS: () => LocalizedString
	/**
	 * Value
	 */
	VALUE: () => LocalizedString
}

export type Formatters = {}
