#!/bin/bash

echo "
                                        
                                        
                      ..,;:;,..         
                  .':lkKNWWWNKxc.       
                .'oKNWNkoccld0WWO;.     
              .'oKWWW0:.    ..oXM0,     
            .'oKWMMXOc.       .kWNl.    
          .'oKWMMMMNKl.       'OMNc.    
        .'oKWMMMMMMMWKo'.  ..;kWWx.     
      .'oKWMMMMMMMMMMMWXkxdx0NWKl.      
     .:0WMMMMMMMMMMMMMMMMMMMWKo'.       
     ;KMMMMMMMMMMMMMMMMMMMWKo'.         
    .oNMMMMMMMMMMMMMMMMMWKo'.           
    .cXMMMMMMMMMMMMMMMWKo'.             
     .dNMMMMMMMMMMMWNKo'.               
      .cONMMMMMMMN0o:'.                 
        .;ldkkkxo:..                    
            ...                         
                                        
                                        
"

echo "-> Loading environment variables from `.env` file"
export $(xargs <.env)

echo "----> HOST: $HOST"
echo "----> PORT: $PORT"
echo "----> DATABASE_URL: $DATABASE_URL"
echo "----> SHOULD_CHECK_VAULT: $SHOULD_CHECK_VAULT"

echo ""
echo "-> Starting server"
node index.js
